apiVersion: apps/v1
kind: Deployment
metadata:
  name: ta-indicators
  labels:
    app: ta-indicators
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ta-indicators
        octopusexport: OctopusExport
    spec:
      hostNetwork: true
      containers:
        - name: ta-indicators
          image: 'tsboris/cbp-ta-indicators:latest'
