apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescale-recorder
  labels:
    app: timescale-recorder
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: timescale-recorder
        octopusexport: OctopusExport
    spec:
      hostNetwork: true
      containers:
        - name: timescale-recorder
          image: 'tsboris/cbp-timescale-recorder:latest'
          env:
            - name: KAFKA_HOST
              value: '10.0.0.124'
            - name: KAFKA_PORT
              value: '9092'
            - name: ELASTIC_HOST
              value: '10.0.0.124'
            - name: ELASTIC_PORT
              value: '9200'
            - name: SQLDB_HOST
              value: '10.0.0.124'
            - name: SQLDB_PORT
              value: '5432'
            - name: SQLDB_NAME
              value: 'cbp'
            - name: SQLDB_USER
              value: 'cbp_user'
            - name: SQLDB_PASS
              value: 'Password1234'
