apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-recorder
  labels:
    app: elastic-recorder
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elastic-recorder
        octopusexport: OctopusExport
    spec:
      hostNetwork: true
      containers:
        - name: elastic-recorder
          image: 'tsboris/cbp-elastic-recorder:latest'
          env:
            - name: KAFKA_HOST
              value: '10.0.0.104'
            - name: KAFKA_PORT
              value: '9092'
            - name: ELASTIC_HOST
              value: '10.0.0.104'
            - name: ELASTIC_PORT
              value: '9200'
