apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-recorder
  labels:
    app: elastic-recorder
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elastic-recorder
        octopusexport: OctopusExport
    spec:
      hostNetwork: true
      containers:
        - name: global-market
          image: 'tsboris/cbp-elastic-recorder:latest'
