apiVersion: apps/v1
kind: Deployment
metadata:
  name: Global market pulser
  labels:
    app: global-market
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: global-market
        octopusexport: OctopusExport
    spec:
      hostNetwork: true
      containers:
        - name: global-market
          image: 'global-market:latest'