apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbp-ftx-public
  labels:
    app: cbp-ftx-public
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 30
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cbp-ftx-public
        octopusexport: OctopusExport
    spec:
      hostNetwork: true
      containers:
        - name: cbp-ftx-public
          image: 'tsboris/cbp-ftx-public:latest'
