apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbp-exchanges-public
  labels:
    app: cbp-exchanges-public
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cbp-exchanges-public
        octopusexport: OctopusExport
    spec:
      hostNetwork: true
      containers:
        - name: cbp-bittrex-public
          image: 'tsboris/cbp-bittrex-public:latest'
        - name: cbp-binanceus-public
          image: 'tsboris/cbp-binanceus-public:latest'
