apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbp-bittrex-public
  labels:
    app: cbp-bittrex-public
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cbp-bittrex-public
        octopusexport: OctopusExport
    spec:
      hostNetwork: true
      containers:
        - name: cbp-bittrex-public
          image: 'tsboris/cbp-bittrex-public:latest'
          env:
            - name: KAFKA_HOST
              value: '10.0.0.124'
            - name: KAFKA_PORT
              value: '9092'
            - name: ELASTIC_HOST
              value: '10.0.0.124'
            - name: ELASTIC_PORT
              value: '9200'
            - name: MONGODB_HOST
              value: '10.0.0.124'
            - name: MONGODB_PORT
              value: '27017'