apiVersion: apps/v1
kind: Deployment
metadata:
  name: Bittrex public exchange
  labels:
    app: cbp-bittrex-public
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cbp-bittrex-public
        octopusexport: OctopusExport
    spec:
      hostNetwork: true
      containers:
        - name: cbp-bittrex-public
          image: 'cbp-bittrex-public:latest'